// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDyIUBpuWIf2FL40Xyf-i_ZiOuWJyhP7YQ',
    appId: '1:166985440014:web:cc63ad5f76439c17bad55f',
    messagingSenderId: '166985440014',
    projectId: 'mimo-todo',
    authDomain: 'mimo-todo.firebaseapp.com',
    storageBucket: 'mimo-todo.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCA9P9dRmURoiKIyBwcHIDXOgYpPoeo9Hw',
    appId: '1:166985440014:android:2aded86d7d51324fbad55f',
    messagingSenderId: '166985440014',
    projectId: 'mimo-todo',
    storageBucket: 'mimo-todo.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyA493tPm36LERkAIKH2wMY0rZyviWFfAnI',
    appId: '1:166985440014:ios:2b8f669fe2e3333cbad55f',
    messagingSenderId: '166985440014',
    projectId: 'mimo-todo',
    storageBucket: 'mimo-todo.appspot.com',
    iosBundleId: 'com.example.memoTodo',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyA493tPm36LERkAIKH2wMY0rZyviWFfAnI',
    appId: '1:166985440014:ios:283d497e132f8224bad55f',
    messagingSenderId: '166985440014',
    projectId: 'mimo-todo',
    storageBucket: 'mimo-todo.appspot.com',
    iosBundleId: 'com.example.memoTodo.RunnerTests',
  );
}
